external_components:
  #- source:
  #    type: git
  #    url: https://github.com/gnumpi/esphome_matrixio
  #    ref: main
  - source:
      type: local
      path: esphome/components/

esphome:
  name: matrixio-voice

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

wifi:
  ssid: SSID
  password: PASSWORD
  fast_connect: true

logger:

ota:

api:

spi:
  clk_pin:  GPIO32
  mosi_pin: GPIO33
  miso_pin: GPIO21

matrixio:
  id: matrixio_dev
  cs_pin: GPIO23

light:
  - platform: matrixio
    name: everloop
    id: everloop

microphone:
  - platform: matrixio
    id: matrixio_mic

speaker:
  - platform: matrixio
    id: matrixio_speaker_hp
    audio_out: headphone
    volume: 90

voice_assistant:
  microphone: matrixio_mic
  speaker: matrixio_speaker_hp
  
  on_listening:
    - light.turn_on:
        id: everloop
        blue: 100%
        red:    0%
        green:  0%
        brightness: 60%
  on_end:
    - light.turn_off:
        id: everloop
  
switch:
  - platform: template
    name: "Voice Control"
    turn_on_action:
      - voice_assistant.start:
          silence_detection: false
    
    turn_off_action:
      - voice_assistant.stop:
